Repository JoshMallery/BranchOut-api, pull requests merged in 2022-06, with the labels that each got.

#9 Feature/create endpoints for courses
  database/migrations/20220530173521_second.js
  database/migrations/20220530214644_third.js
  database/migrations/20220530225313_fourth.js
  database/migrations/20220530230752_fith.js
  database/migrations/20220531003043_sixth.js
  database/migrations/20220531015722_seventh.js
  database/seeds/dev/courses.js
  index.js
Labels: enhancement

#10 Installs cors as a dependancy
  index.js
  node_modules/.package-lock.json
  node_modules/cors/CONTRIBUTING.md
  node_modules/cors/HISTORY.md
  node_modules/cors/LICENSE
  node_modules/cors/README.md
  node_modules/cors/lib/index.js
  node_modules/cors/package.json
  node_modules/object-assign/index.js
  node_modules/object-assign/license
  node_modules/object-assign/package.json
  node_modules/object-assign/readme.md
  package-lock.json
  package.json
Labels: enhancement, MVP

#13 Created back-end readMe
  README.md
Labels: documentation, MVP

#12 Replaces existing seed data with better data
  database/data/coursesData.js
  database/seeds/dev/courses.js
Labels: enhancement
